name: PR Test (XPU)

on:
  push:
    branches: [ main ]
    paths:
      - "python/**"
      - "scripts/ci/**"
      - "test/**"
      - "sgl-kernel/**"
      - ".github/workflows/pr-test-xpu.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "python/**"
      - "scripts/ci/**"
      - "test/**"
      - "sgl-kernel/**"
      - ".github/workflows/pr-test-xpu.yml"
    types: [synchronize, labeled]
  workflow_dispatch:

concurrency:
  group: pr-test-xpu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: intel-bmg
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker build \
            --build-arg SG_LANG_BRANCH=${{ github.head_ref }} \
            --build-arg SG_LANG_REPO=${{ github.event.pull_request.head.repo.clone_url }} \
            --no-cache --progress=plain -f docker/Dockerfile.xpu -t xpu_sglang_main:bmg .


      - name: Run container
        run: |
          docker run -dt \
            --device /dev/dri/ \
            --name main_sglang_xpu \
            -e HF_TOKEN=$(cat ~/huggingface_token.txt) \
            xpu_sglang_main:bmg

      - name: Install Dependency
        timeout-minutes: 20
        run: |
          docker exec main_sglang_xpu /home/sdp/miniforge3/envs/py3.10/bin/python3 -m pip install --upgrade pip
          docker exec main_sglang_xpu /home/sdp/miniforge3/envs/py3.10/bin/python3 -m pip install pytest expecttest ray huggingface_hub
          docker exec main_sglang_xpu /home/sdp/miniforge3/envs/py3.10/bin/python3 -m pip uninstall -y flashinfer-python
          docker exec main_sglang_xpu /bin/bash -c '/home/sdp/miniforge3/envs/py3.10/bin/huggingface-cli login --token ${HF_TOKEN} '
          docker exec -u root main_sglang_xpu /bin/bash -c "ln -sf /home/sdp/miniforge3/envs/py3.10/bin/python3 /usr/bin/python3"

      - name: Run E2E Bfloat16 tests
        timeout-minutes: 20
        run: |
          docker exec -w /home/sdp/sglang/ main_sglang_xpu \
            bash -c "cd ./test/srt && python3 run_suite.py --suite per-commit-xpu"

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f main_sglang_xpu || true

  finish:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "Job failed with result: ${{ needs.build-and-test.result }}"
            echo "BUILD_LOG=$(cat build.log)" >> $GITHUB_ENV
            exit 1
          fi
          echo "All jobs completed successfully"
          exit 0
